tar_git: Allow to generate changelog with supplied executable
Allow packages to provide rpm/NAME.changes.run executable in order to
customize their changelog generation.

diff --git a/src/service/tar_git b/src/service/tar_git
--- a/src/service/tar_git
+++ b/src/service/tar_git
@@ -53,6 +53,8 @@ set_default_params () {
   LOCAL_SUBMODULES="N"
   LOCAL_GROUPS="mer-core mer-core-attic mer-crosshelpers mer-obs mer-tools"  
   LOCAL_MIRROR_GROUP="mirror"
+  ALLOW_CHANGES_RUN=""
+  CHANGES_RUN_WRAPPER=()
 }
 
 get_config_options () {
@@ -76,6 +78,9 @@ usage () {
     echo '	--debian	Y/N switch to turn on debian packaging support (defaults to N)'
     echo '	--fileserver    baseurl of a location for fetching files listed in a _sources file in the rpm subdir'
     echo '	--dumb          Y/N switch to take content of revision as-is without automatic processing'
+    echo '	--allow-changes-run[=<wrapper>]   allow running supplied executable to generate changelog.'
+    echo '	                                  Optionally use the given exec <wrapper> to protect against malware.'
+    echo '	                                  <wrapper> can be a command with initial list of arguments'
     echo 'If your git repo has multiple spec files in the rpm subdirectory set the env variable OBS_SERVICE_PACKAGE '
     echo 'to the name of the one you want to use (without .spec suffix)'
     echo 'The _sources file is expected to contain lines of <sha1sum> <subdir>/<filename>'
@@ -116,6 +121,13 @@ parse_params () {
       *-fileserver)
         FILESERVER="$2"
         shift
+      ;;
+      *-allow-changes-run)
+        ALLOW_CHANGES_RUN=1
+      ;;
+      *-allow-changes-run=*)
+        ALLOW_CHANGES_RUN=1
+        eval CHANGES_RUN_WRAPPER=(${1#*=})
       ;;
       *-help)
         usage
@@ -227,6 +239,13 @@ find_changes_file () {
   [[ -z $CHANGESFILE ]] || cp "$CHANGESFILE" ..
 }
 
+find_changes_run_file () {
+
+  CHANGESRUNFILE="$(find $1 -type f -name '*.changes.run')"
+
+  [[ "$(echo $CHANGESRUNFILE | wc -w)" -le 1 ]] || error "Need single changes.run file in rpm"
+}
+
 find_yaml_file () {
 
   YAMLFILE="$(basename $SPECFILE .spec).yaml"
@@ -237,7 +256,7 @@ find_yaml_file () {
 
 find_other_files () {
 
-  for i in $(find rpm/ -type f -not -name '*.yaml' -not -name '*.changes' -not -name '*.spec'); do
+  for i in $(find rpm/ -type f -not -name '*.yaml' -not -name '*.changes' -not -name '*.changes.run' -not -name '*.spec'); do
 
     cp -v $i ..
 
@@ -531,6 +550,17 @@ do_changelog_block () {
 }
 
 generate_changes () {
+
+  if test -n "$CHANGESRUNFILE"; then
+    if test -z "$ALLOW_CHANGES_RUN"; then
+      error "Not allowed to run supplied executable to generate changelog"
+    fi
+    CHANGESFILE=../$(basename "${CHANGESRUNFILE%.run}")
+    if ! command "${CHANGES_RUN_WRAPPER[@]}" "$CHANGESRUNFILE" > "$CHANGESFILE"; then
+      error "Unable to generate changelog entries using '$CHANGESRUNFILE'"
+    fi
+    return
+  fi
 
   CHANGES=""
   ENTRIES=""
@@ -979,6 +1009,7 @@ rpm_pkg () {
   expand_spec_file "$SPECFILE"
   cp -v "$SPECFILE" ..
   find_changes_file rpm
+  find_changes_run_file rpm
   find_yaml_file
   find_other_files
   find_compression "$SPECFILE"
@@ -1029,6 +1060,7 @@ run_android_repo_service () {
   $REPOCMD
   find_spec_file "$MYOUTDIR"
   find_changes_file "$MYOUTDIR"
+  find_changes_run_file "$MYOUTDIR"
   find_package_name "$SPECFILE"
   echo "package name is $PACKAGE_NAME"
   set_versha
